version: '{build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  QT5_ROOT_DIR: c:\beam-libs\qt5-static-win
  QML_IMPORT_PATH: c:\beam-libs\qt5-static-win\qml
  BUILD_SERVER:
    secure: l9RqB2YbSnNIKZqTwnd67BHAXvbjmpj9zcf+YQPi9zfzsVeSysaoLD7gy4gSMjWurk2JVHjRpviw4bBxUbu2sA==  
  BUILD_CONFIG: RelWithDebInfo
  PATH: c:\beam-libs\qt5-static-win\bin;$(PATH)
 
before_build:
  - cmd: git clone --depth=1 https://github.com/BeamMW/libs.git c:/beam-libs
  - cmd: git clone --depth=1 https://github.com/nesbox/qt5-static-win.git c:/beam-libs/qt5-static-win
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH% -DLITECASH_BUILD_JNI=On .

test_script:
  - cmd: ctest -C %BUILD_CONFIG% --verbose

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

after_build:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- ps: $env:LITECASH_TARGET_SUFFIX=''
- ps: $env:LITECASH_DISPLAY_SUFFIX=''
- ps: $env:LITECASH_DISPLAY_SUFFIX2=''
- ps: $env:LITECASH_DISPLAY_SUFFIX3=''
- cmd: >-
    cpack --verbose -G NSIS -C %BUILD_CONFIG%
    
    set /p LITECASH_VERSION=<beam_version.gen

    echo LITECASH_VERSION = %LITECASH_VERSION%

    del beam_version.gen
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%LITECASH_TARGET_SUFFIX%.exe c:/projects/beam/beam/beam-node.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:/projects/beam/wallet/%BUILD_CONFIG%/beam-wallet%LITECASH_TARGET_SUFFIX%.exe c:/projects/beam/wallet/beam-wallet.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:/projects/beam/wallet/%BUILD_CONFIG%/wallet-api%LITECASH_TARGET_SUFFIX%.exe c:/projects/beam/wallet/wallet-api.cfg

    7z a c:/projects/beam/beam/%BUILD_CONFIG%/explorer-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:/projects/beam/explorer/%BUILD_CONFIG%/explorer-node%LITECASH_TARGET_SUFFIX%.exe c:/projects/beam/explorer/explorer-node.cfg
        
    mkdir pdb
    
    7z a c:/projects/beam/beam/beam-pdb%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip "c:/projects/beam/ui/%BUILD_CONFIG%/Beam Wallet%LITECASH_DISPLAY_SUFFIX3%.pdb" "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%LITECASH_TARGET_SUFFIX%.pdb" "c:/projects/beam/wallet/%BUILD_CONFIG%/beam-wallet%LITECASH_TARGET_SUFFIX%.pdb"

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:\projects\beam\beam-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-wallet-cli%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:\projects\beam\beam-wallet-cli%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\wallet-api%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:\projects\beam\wallet-api%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\explorer-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:\projects\beam\explorer-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip

    copy c:\projects\beam\beam\beam-pdb%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip c:\projects\beam\pdb\beam-pdb%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip

    copy c:\projects\beam\BeamWallet%LITECASH_DISPLAY_SUFFIX%-%LITECASH_VERSION%-win64.exe c:\projects\beam\Beam-Wallet%LITECASH_DISPLAY_SUFFIX2%-%LITECASH_VERSION%.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win
              
    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip" "%BUILDS_SERVER_PATH%/beam-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip" "%BUILDS_SERVER_PATH%/beam-wallet-cli%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip" "%BUILDS_SERVER_PATH%/wallet-api%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/explorer-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip" "%BUILDS_SERVER_PATH%/explorer-node%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/BeamWallet%LITECASH_DISPLAY_SUFFIX%-%LITECASH_VERSION%-win64.exe" "%BUILDS_SERVER_PATH%/Beam-Wallet%LITECASH_DISPLAY_SUFFIX2%-%LITECASH_VERSION%.exe"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/beam-pdb%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip" "%BUILDS_SERVER_PATH%/pdb/beam-pdb%LITECASH_TARGET_SUFFIX%-%LITECASH_VERSION%.zip"

artifacts:
  - path: beam-node-%LITECASH_VERSION%.zip
    name: BeamNode

  - path: beam-wallet-cli-%LITECASH_VERSION%.zip
    name: BeamWalletCli

  - path: wallet-api-%LITECASH_VERSION%.zip
    name: BeamWalletApi

  - path: explorer-node-%LITECASH_VERSION%.zip
    name: BeamNodeExplorer

  - path: pdb/beam-pdb-%LITECASH_VERSION%.zip
    name: BeamPdb

  - path: Beam-Wallet-%LITECASH_VERSION%.exe
    name: BeamWallet

deploy:
  provider: S3
  access_key_id:
    secure: J8+/d4TSbhxiaFlDQopFzKbfLPvUy1rMUJlAgnfbBNE=
  secret_access_key:
    secure: sqF9zdsuUm/k9QzY46s250MZJamHjKrwBCAPbinBA/iOJlgLsHC7lq1F5pTr/B+U
  bucket: builds.beam.mw
  region: us-west-2
  unzip: false
  set_public: true
  folder: "%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win/"
  artifact: BeamPdb, BeamWalletApi, BeamNodeExplorer, BeamWalletCli, BeamNode, BeamWallet

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
